Feat/jr/metrics
Informasjonsforvaltning/fdk-rdf-parse-event-publisher pull request #7
Opened 2024-03-14 09:22 UTC by jeffreiffers

Fixes #6

2024-03-14 09:25 UTC, NilsOveTen approved these changes

2024-03-18 08:55 UTC, terjesyl requested changes

2024-03-18 08:55 UTC, terjesyl commented on src/main/kotlin/no/digdir/fdk/rdf/parse/eventpublisher/kafka/KafkaReasonedEventConsumer.kt
> +                    parseAndProduce(it.fdkId.toString(), it.graph.toString(), it.timestamp, resourceType!!)
Kan `resourceType` gjøres non-nullable i stedet for? Og hvis den må være nullable, er det ikke bedre å sjekke og håndtere hvis den er null?

2024-03-19 07:10 UTC, terjesyl approved these changes

2024-03-19 13:41 UTC, pooriamehregan approved these changes

2024-03-21 13:52 UTC, valosnah approved these changes

2024-03-22 09:57 UTC, merged